### PR TITLE
Support Initial Pose from RViz Panel

### PR DESCRIPTION
**Pull request by tzu-lin-huang-128**
Dear Sasaki,

I wanted to let you know that we are now able to set the initial pose from the RViz Panel. 
The pull request has disabled all the code related to "path_pub_" for debugging purposes.

Thanks

### CODE REVIEW

**Comment by tzu-lin-huang-128** [comment]
Dear Sasaki, 

I wanted to give you an update on the pull request I recently submitted for the pcl_localization_ros2 package. With this update, users will be able to set the initial pose from the RViz Panel, which should improve the localization process. However, I also wanted to inform you that the lidar sensor is tilted at an angle, which may be contributing to some alignment issues during the localization process. 

Although I disabled the "tf" publisher for debugging purposes, I am confident that there is another "tf" publisher in place to handle the transform from the lidar sensor to base_footprint or base_link. 

I have attached a video clip of the localization process for your reference. Could you please review it and let me know your thoughts? If necessary, I would be happy to submit a new pull request to fix any issues once we have resolved the tilt angle problem. 

Thank you for your time and assistance.


(Note: There is no issue when using NDT localization with ROS1 Ubuntu 18.04 (Autoware) on the same lidar input and map data.)

**Comment by rsasaki0109** [comment]
Is the video you provided the result of publish initilal pose from the rviz panel?
If so, the problem may be that the initilal pose from the rviz panel has a z of 0.

**Comment by rsasaki0109** [comment]
Then maybe the version of pcl has been upgraded and a bug was introduced into pcl ndt in the process.

**Comment by rsasaki0109** [comment]
Sorry for the delay, but I’ve merged it now. Thanks again for the PR!

**Pull request merged**
